name: gScanner
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_icons: ^1.1.0
  flutter_speed_dial: ^1.2.5

  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1

  intl: ^0.16.1
  http: ^0.12.2
  pdf: ^2.0.0
  printing: ^4.0.0
  path_provider: ^1.6.27

  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0

  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9

  provider: ^4.3.2+4

  flare_flutter: ^2.0.6
  flare_splash_screen: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
